import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Theme = 'light' | 'dark' | 'midnight' | 'gold';
export type Language = 'fr' | 'en' | 'es' | 'ht';

interface AppState {
  theme: Theme;
  language: Language;
  token: string | null;
  setTheme: (theme: Theme) => void;
  setLanguage: (lang: Language) => void;
  setToken: (token: string | null) => void;
  logout: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'nav.dashboard': 'Tableau de bord',
    'nav.wallet': 'Bourse',
    'nav.boards': 'Boards',
    'nav.how_it_works': 'Comment ça marche',
    'nav.history': 'Historique',
    'nav.referrals': 'Parrainage',
    'nav.notifications': 'Notifications',
    'nav.profile': 'Profil',
    'nav.admin': 'Admin',
    'nav.logout': 'Déconnexion',

    'wallet.balance': 'Solde Disponible',
    'wallet.pending': 'En attente',
    'wallet.reserved': 'Réservé',
    'wallet.total': 'Total',
    'wallet.deposit': 'Déposer',
    'wallet.withdraw': 'Retirer',
    'wallet.convert': 'Convertir',
    'wallet.method': 'Méthode de paiement',
    'wallet.amount': 'Montant',
    'wallet.currency': 'Devise',
    'wallet.reference': 'Référence',
    'wallet.submit': 'Soumettre',
    'wallet.pending_review': 'En attente de validation',

    'dashboard.greeting': 'Bienvenue',
    'dashboard.balance_title': 'Solde disponible',
    'dashboard.current_board': 'Board actuel',
    'dashboard.recent_activity': 'Activité récente',
    'dashboard.deposit': 'Déposer',
    'dashboard.go_boards': 'Voir les Boards',
    'dashboard.view_pyramid': 'Voir la Pyramide',
    'dashboard.join_starter': 'Rejoindre le Board de départ',
    'dashboard.not_in_board': 'Pas encore dans un board actif.',
    'dashboard.no_activity': 'Aucune activité récente.',

    'boards.title': 'Pyramid Boards',
    'boards.subtitle': '7 niveaux progressifs — de F à S',
    'boards.select': 'Sélectionner',
    'boards.pay': 'Payer la cotisation',
    'boards.fee': 'Cotisation',
    'boards.gain': 'Gain total',
    'boards.members': 'membres',
    'boards.join': 'Rejoindre ce Board',
    'boards.insufficient': 'Solde insuffisant',
    'boards.already_in': 'Déjà membre',
    'boards.completed': 'Complété',
    'boards.pending': 'En attente',

    'auth.login': 'Connexion',
    'auth.register': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.username': 'Nom d\'utilisateur',
    'auth.first_name': 'Prénom',
    'auth.last_name': 'Nom',
    'auth.referral_code': 'Code de parrainage (obligatoire)',
    'auth.forgot_password': 'Mot de passe oublié ?',
    'auth.no_account': 'Pas encore de compte ?',
    'auth.have_account': 'Déjà un compte ?',
    'auth.sign_in': 'Se connecter',
    'auth.create_account': 'Créer un compte',
    'auth.register_now': 'S\'inscrire maintenant',
    'auth.login_instead': 'Se connecter',

    'verify.title': 'Vérifiez votre email',
    'verify.subtitle': 'Un code de vérification a été envoyé à',
    'verify.enter_code': 'Entrez le code à 6 chiffres',
    'verify.resend': 'Renvoyer le code',
    'verify.resend_in': 'Renvoyer dans',
    'verify.verify': 'Vérifier',
    'verify.back': 'Retour à la connexion',

    'onboarding.step1': 'Choisissez votre langue',
    'onboarding.step2': 'Choisissez votre thème',
    'onboarding.step3': 'Configurez votre profil',
    'onboarding.step4': 'Votre code de parrainage',
    'onboarding.continue': 'Continuer',
    'onboarding.finish': 'Terminer l\'installation',
    'onboarding.welcome': 'Bienvenue sur Ecrossflow',
    'onboarding.step_of': 'Étape',
    'onboarding.of': 'sur',

    'history.title': 'Historique',
    'history.subtitle': 'Toutes vos transactions',
    'history.all': 'Toutes',
    'history.deposit': 'Dépôt',
    'history.withdrawal': 'Retrait',
    'history.board_payment': 'Paiement Board',
    'history.board_receipt': 'Gain Board',
    'history.referral_bonus': 'Bonus Parrainage',
    'history.system_fee': 'Frais Système',
    'history.no_transactions': 'Aucune transaction trouvée',
    'history.previous': '← Précédent',
    'history.next': 'Suivant →',
    'history.page': 'Page',

    'referrals.title': 'Parrainage',
    'referrals.subtitle': 'Invitez vos amis et gagnez des bonus',
    'referrals.your_code': 'Votre code de parrainage',
    'referrals.copy_code': 'Copier le code',
    'referrals.copy_link': 'Copier le lien',
    'referrals.copied': 'Copié !',
    'referrals.total': 'Total filleuls',
    'referrals.active': 'Filleuls actifs',
    'referrals.bonus': 'Bonus total',
    'referrals.no_referrals': 'Aucun filleul pour l\'instant',
    'referrals.share': 'Partagez votre code pour commencer !',

    'notifications.title': 'Notifications',
    'notifications.all': 'Toutes',
    'notifications.unread': 'Non lues',
    'notifications.financial': 'Finance',
    'notifications.security': 'Sécurité',
    'notifications.mark_all': 'Tout marquer lu',
    'notifications.none': 'Aucune notification',

    'profile.title': 'Profil',
    'profile.subtitle': 'Vos informations et préférences',
    'profile.account_number': 'Numéro de compte',
    'profile.email': 'Email',
    'profile.phone': 'Téléphone',
    'profile.current_board': 'Board actuel',
    'profile.referral_code': 'Code de parrainage',
    'profile.member_since': 'Membre depuis',
    'profile.theme': 'Thème',
    'profile.language': 'Langue',
    'profile.save': 'Sauvegarder',
    'profile.not_set': 'Non renseigné',

    'common.loading': 'Chargement...',
    'common.error': 'Une erreur est survenue',
    'common.back': '← Retour',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.save': 'Sauvegarder',
    'common.close': 'Fermer',
    'common.or': 'ou',
    'common.usd': 'USD',
    'common.status_active': 'Actif',
    'common.status_pending': 'En attente',
    'common.status_suspended': 'Suspendu',
  },
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.wallet': 'Wallet',
    'nav.boards': 'Boards',
    'nav.how_it_works': 'How it Works',
    'nav.history': 'History',
    'nav.referrals': 'Referrals',
    'nav.notifications': 'Notifications',
    'nav.profile': 'Profile',
    'nav.admin': 'Admin',
    'nav.logout': 'Logout',

    'wallet.balance': 'Available Balance',
    'wallet.pending': 'Pending',
    'wallet.reserved': 'Reserved',
    'wallet.total': 'Total',
    'wallet.deposit': 'Deposit',
    'wallet.withdraw': 'Withdraw',
    'wallet.convert': 'Convert',
    'wallet.method': 'Payment method',
    'wallet.amount': 'Amount',
    'wallet.currency': 'Currency',
    'wallet.reference': 'Reference',
    'wallet.submit': 'Submit',
    'wallet.pending_review': 'Pending review',

    'dashboard.greeting': 'Welcome',
    'dashboard.balance_title': 'Available balance',
    'dashboard.current_board': 'Current board',
    'dashboard.recent_activity': 'Recent activity',
    'dashboard.deposit': 'Deposit',
    'dashboard.go_boards': 'Go to Boards',
    'dashboard.view_pyramid': 'View Pyramid',
    'dashboard.join_starter': 'Join Starter Board',
    'dashboard.not_in_board': 'Not in any active board.',
    'dashboard.no_activity': 'No recent activity.',

    'boards.title': 'Pyramid Boards',
    'boards.subtitle': '7 progressive levels — F to S',
    'boards.select': 'Select',
    'boards.pay': 'Pay entry fee',
    'boards.fee': 'Entry fee',
    'boards.gain': 'Total gain',
    'boards.members': 'members',
    'boards.join': 'Join this Board',
    'boards.insufficient': 'Insufficient balance',
    'boards.already_in': 'Already a member',
    'boards.completed': 'Completed',
    'boards.pending': 'Pending',

    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.username': 'Username',
    'auth.first_name': 'First name',
    'auth.last_name': 'Last name',
    'auth.referral_code': 'Referral code (required)',
    'auth.forgot_password': 'Forgot password?',
    'auth.no_account': 'Don\'t have an account?',
    'auth.have_account': 'Already have an account?',
    'auth.sign_in': 'Sign in',
    'auth.create_account': 'Create account',
    'auth.register_now': 'Register now',
    'auth.login_instead': 'Log in instead',

    'verify.title': 'Verify your email',
    'verify.subtitle': 'A verification code was sent to',
    'verify.enter_code': 'Enter the 6-digit code',
    'verify.resend': 'Resend code',
    'verify.resend_in': 'Resend in',
    'verify.verify': 'Verify',
    'verify.back': 'Back to login',

    'onboarding.step1': 'Choose your language',
    'onboarding.step2': 'Choose your theme',
    'onboarding.step3': 'Set up your profile',
    'onboarding.step4': 'Your referral code',
    'onboarding.continue': 'Continue',
    'onboarding.finish': 'Finish setup',
    'onboarding.welcome': 'Welcome to Ecrossflow',
    'onboarding.step_of': 'Step',
    'onboarding.of': 'of',

    'history.title': 'History',
    'history.subtitle': 'All your transactions',
    'history.all': 'All',
    'history.deposit': 'Deposit',
    'history.withdrawal': 'Withdrawal',
    'history.board_payment': 'Board Payment',
    'history.board_receipt': 'Board Receipt',
    'history.referral_bonus': 'Referral Bonus',
    'history.system_fee': 'System Fee',
    'history.no_transactions': 'No transactions found',
    'history.previous': '← Previous',
    'history.next': 'Next →',
    'history.page': 'Page',

    'referrals.title': 'Referrals',
    'referrals.subtitle': 'Invite friends and earn bonuses',
    'referrals.your_code': 'Your referral code',
    'referrals.copy_code': 'Copy code',
    'referrals.copy_link': 'Copy link',
    'referrals.copied': 'Copied!',
    'referrals.total': 'Total referrals',
    'referrals.active': 'Active referrals',
    'referrals.bonus': 'Total bonus',
    'referrals.no_referrals': 'No referrals yet',
    'referrals.share': 'Share your code to get started!',

    'notifications.title': 'Notifications',
    'notifications.all': 'All',
    'notifications.unread': 'Unread',
    'notifications.financial': 'Financial',
    'notifications.security': 'Security',
    'notifications.mark_all': 'Mark all as read',
    'notifications.none': 'No notifications',

    'profile.title': 'Profile',
    'profile.subtitle': 'Your information and preferences',
    'profile.account_number': 'Account number',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.current_board': 'Current board',
    'profile.referral_code': 'Referral code',
    'profile.member_since': 'Member since',
    'profile.theme': 'Theme',
    'profile.language': 'Language',
    'profile.save': 'Save',
    'profile.not_set': 'Not set',

    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.back': '← Back',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.close': 'Close',
    'common.or': 'or',
    'common.usd': 'USD',
    'common.status_active': 'Active',
    'common.status_pending': 'Pending',
    'common.status_suspended': 'Suspended',
  },
  es: {
    'nav.dashboard': 'Panel',
    'nav.wallet': 'Billetera',
    'nav.boards': 'Tableros',
    'nav.how_it_works': 'Cómo funciona',
    'nav.history': 'Historial',
    'nav.referrals': 'Referidos',
    'nav.notifications': 'Notificaciones',
    'nav.profile': 'Perfil',
    'nav.admin': 'Admin',
    'nav.logout': 'Salir',

    'wallet.balance': 'Saldo Disponible',
    'wallet.pending': 'Pendiente',
    'wallet.reserved': 'Reservado',
    'wallet.total': 'Total',
    'wallet.deposit': 'Depositar',
    'wallet.withdraw': 'Retirar',
    'wallet.convert': 'Convertir',
    'wallet.method': 'Método de pago',
    'wallet.amount': 'Monto',
    'wallet.currency': 'Divisa',
    'wallet.reference': 'Referencia',
    'wallet.submit': 'Enviar',
    'wallet.pending_review': 'En revisión',

    'dashboard.greeting': 'Bienvenido',
    'dashboard.balance_title': 'Saldo disponible',
    'dashboard.current_board': 'Tablero actual',
    'dashboard.recent_activity': 'Actividad reciente',
    'dashboard.deposit': 'Depositar',
    'dashboard.go_boards': 'Ir a Tableros',
    'dashboard.view_pyramid': 'Ver Pirámide',
    'dashboard.join_starter': 'Unirse al Tablero inicial',
    'dashboard.not_in_board': 'No estás en ningún tablero activo.',
    'dashboard.no_activity': 'Sin actividad reciente.',

    'boards.title': 'Tableros Pirámide',
    'boards.subtitle': '7 niveles progresivos — de F a S',
    'boards.select': 'Seleccionar',
    'boards.pay': 'Pagar cuota',
    'boards.fee': 'Cuota de entrada',
    'boards.gain': 'Ganancia total',
    'boards.members': 'miembros',
    'boards.join': 'Unirse a este Tablero',
    'boards.insufficient': 'Saldo insuficiente',
    'boards.already_in': 'Ya eres miembro',
    'boards.completed': 'Completado',
    'boards.pending': 'Pendiente',

    'auth.login': 'Iniciar sesión',
    'auth.register': 'Registrarse',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.username': 'Nombre de usuario',
    'auth.first_name': 'Nombre',
    'auth.last_name': 'Apellido',
    'auth.referral_code': 'Código de referido (obligatorio)',
    'auth.forgot_password': '¿Olvidaste tu contraseña?',
    'auth.no_account': '¿No tienes cuenta?',
    'auth.have_account': '¿Ya tienes cuenta?',
    'auth.sign_in': 'Iniciar sesión',
    'auth.create_account': 'Crear cuenta',
    'auth.register_now': 'Registrarse ahora',
    'auth.login_instead': 'Iniciar sesión',

    'verify.title': 'Verifica tu correo',
    'verify.subtitle': 'Se envió un código de verificación a',
    'verify.enter_code': 'Ingresa el código de 6 dígitos',
    'verify.resend': 'Reenviar código',
    'verify.resend_in': 'Reenviar en',
    'verify.verify': 'Verificar',
    'verify.back': 'Volver al inicio',

    'onboarding.step1': 'Elige tu idioma',
    'onboarding.step2': 'Elige tu tema',
    'onboarding.step3': 'Configura tu perfil',
    'onboarding.step4': 'Tu código de referido',
    'onboarding.continue': 'Continuar',
    'onboarding.finish': 'Finalizar configuración',
    'onboarding.welcome': 'Bienvenido a Ecrossflow',
    'onboarding.step_of': 'Paso',
    'onboarding.of': 'de',

    'history.title': 'Historial',
    'history.subtitle': 'Todas tus transacciones',
    'history.all': 'Todas',
    'history.deposit': 'Depósito',
    'history.withdrawal': 'Retiro',
    'history.board_payment': 'Pago de Tablero',
    'history.board_receipt': 'Recibo de Tablero',
    'history.referral_bonus': 'Bono de Referido',
    'history.system_fee': 'Tarifa del Sistema',
    'history.no_transactions': 'No se encontraron transacciones',
    'history.previous': '← Anterior',
    'history.next': 'Siguiente →',
    'history.page': 'Página',

    'referrals.title': 'Referidos',
    'referrals.subtitle': 'Invita amigos y gana bonos',
    'referrals.your_code': 'Tu código de referido',
    'referrals.copy_code': 'Copiar código',
    'referrals.copy_link': 'Copiar enlace',
    'referrals.copied': '¡Copiado!',
    'referrals.total': 'Total referidos',
    'referrals.active': 'Referidos activos',
    'referrals.bonus': 'Bono total',
    'referrals.no_referrals': 'Aún no tienes referidos',
    'referrals.share': '¡Comparte tu código para comenzar!',

    'notifications.title': 'Notificaciones',
    'notifications.all': 'Todas',
    'notifications.unread': 'No leídas',
    'notifications.financial': 'Financiero',
    'notifications.security': 'Seguridad',
    'notifications.mark_all': 'Marcar todo como leído',
    'notifications.none': 'Sin notificaciones',

    'profile.title': 'Perfil',
    'profile.subtitle': 'Tu información y preferencias',
    'profile.account_number': 'Número de cuenta',
    'profile.email': 'Correo',
    'profile.phone': 'Teléfono',
    'profile.current_board': 'Tablero actual',
    'profile.referral_code': 'Código de referido',
    'profile.member_since': 'Miembro desde',
    'profile.theme': 'Tema',
    'profile.language': 'Idioma',
    'profile.save': 'Guardar',
    'profile.not_set': 'No configurado',

    'common.loading': 'Cargando...',
    'common.error': 'Ocurrió un error',
    'common.back': '← Atrás',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Guardar',
    'common.close': 'Cerrar',
    'common.or': 'o',
    'common.usd': 'USD',
    'common.status_active': 'Activo',
    'common.status_pending': 'Pendiente',
    'common.status_suspended': 'Suspendido',
  },
  ht: {
    'nav.dashboard': 'Dachbòd',
    'nav.wallet': 'Bous',
    'nav.boards': 'Bòd yo',
    'nav.how_it_works': 'Kijan sa travay',
    'nav.history': 'Istwa',
    'nav.referrals': 'Parennaj',
    'nav.notifications': 'Notifikasyon',
    'nav.profile': 'Pwofil',
    'nav.admin': 'Admin',
    'nav.logout': 'Dekonekte',

    'wallet.balance': 'Balans ki disponib',
    'wallet.pending': 'An atant',
    'wallet.reserved': 'Rezève',
    'wallet.total': 'Total',
    'wallet.deposit': 'Depoze',
    'wallet.withdraw': 'Retire',
    'wallet.convert': 'Konvèti',
    'wallet.method': 'Metòd pèman',
    'wallet.amount': 'Montan',
    'wallet.currency': 'Devis',
    'wallet.reference': 'Referans',
    'wallet.submit': 'Voye',
    'wallet.pending_review': 'An atant verifikasyon',

    'dashboard.greeting': 'Byenveni',
    'dashboard.balance_title': 'Balans disponib',
    'dashboard.current_board': 'Bòd aktyèl',
    'dashboard.recent_activity': 'Aktivite resan',
    'dashboard.deposit': 'Depoze',
    'dashboard.go_boards': 'Al nan Bòd yo',
    'dashboard.view_pyramid': 'Wè Piramid',
    'dashboard.join_starter': 'Rantre nan premye Bòd',
    'dashboard.not_in_board': 'Pa nan okenn bòd aktif.',
    'dashboard.no_activity': 'Pa gen aktivite resan.',

    'boards.title': 'Piramid Bòd yo',
    'boards.subtitle': '7 nivo progresif — F pou rive S',
    'boards.select': 'Chwazi',
    'boards.pay': 'Peye kotizan',
    'boards.fee': 'Kotizan',
    'boards.gain': 'Benefis total',
    'boards.members': 'manm',
    'boards.join': 'Rantre nan Bòd sa a',
    'boards.insufficient': 'Balans ensifizant',
    'boards.already_in': 'Deja manm',
    'boards.completed': 'Konplete',
    'boards.pending': 'An atant',

    'auth.login': 'Konekte',
    'auth.register': 'Enskri',
    'auth.email': 'Imèl',
    'auth.password': 'Modpas',
    'auth.username': 'Non itilizatè',
    'auth.first_name': 'Prenon',
    'auth.last_name': 'Siyati',
    'auth.referral_code': 'Kòd parennaj (obligatwa)',
    'auth.forgot_password': 'Bliye modpas?',
    'auth.no_account': 'Pa gen kont?',
    'auth.have_account': 'Genyen kont deja?',
    'auth.sign_in': 'Konekte',
    'auth.create_account': 'Kreye kont',
    'auth.register_now': 'Enskri kounye a',
    'auth.login_instead': 'Konekte',

    'verify.title': 'Verifye imèl ou',
    'verify.subtitle': 'Yo voye yon kòd verifikasyon bay',
    'verify.enter_code': 'Antre kòd 6 chif la',
    'verify.resend': 'Voye kòd ankò',
    'verify.resend_in': 'Voye ankò nan',
    'verify.verify': 'Verifye',
    'verify.back': 'Retounen nan koneksyon',

    'onboarding.step1': 'Chwazi lang ou',
    'onboarding.step2': 'Chwazi tèm ou',
    'onboarding.step3': 'Konfigire pwofil ou',
    'onboarding.step4': 'Kòd parennaj ou',
    'onboarding.continue': 'Kontinye',
    'onboarding.finish': 'Fini konfigirasyon',
    'onboarding.welcome': 'Byenveni sou Ecrossflow',
    'onboarding.step_of': 'Etap',
    'onboarding.of': 'nan',

    'history.title': 'Istwa',
    'history.subtitle': 'Tout tranzaksyon ou yo',
    'history.all': 'Tout',
    'history.deposit': 'Depo',
    'history.withdrawal': 'Retrè',
    'history.board_payment': 'Pèman Bòd',
    'history.board_receipt': 'Resi Bòd',
    'history.referral_bonus': 'Bonis Parennaj',
    'history.system_fee': 'Frè Sistèm',
    'history.no_transactions': 'Pa jwenn tranzaksyon',
    'history.previous': '← Anvan',
    'history.next': 'Swivan →',
    'history.page': 'Paj',

    'referrals.title': 'Parennaj',
    'referrals.subtitle': 'Envite zanmi ou yo epi rantre bonis',
    'referrals.your_code': 'Kòd parennaj ou',
    'referrals.copy_code': 'Kopye kòd',
    'referrals.copy_link': 'Kopye lyen',
    'referrals.copied': 'Kopye !',
    'referrals.total': 'Total filèl',
    'referrals.active': 'Filèl aktif',
    'referrals.bonus': 'Bonis total',
    'referrals.no_referrals': 'Pa gen filèl pou kounye a',
    'referrals.share': 'Pataje kòd ou pou kòmanse !',

    'notifications.title': 'Notifikasyon',
    'notifications.all': 'Tout',
    'notifications.unread': 'Pa li',
    'notifications.financial': 'Finansye',
    'notifications.security': 'Sekirite',
    'notifications.mark_all': 'Mete tout tankou li',
    'notifications.none': 'Pa gen notifikasyon',

    'profile.title': 'Pwofil',
    'profile.subtitle': 'Enfòmasyon ak preferans ou',
    'profile.account_number': 'Nimewo kont',
    'profile.email': 'Imèl',
    'profile.phone': 'Telefòn',
    'profile.current_board': 'Bòd aktyèl',
    'profile.referral_code': 'Kòd parennaj',
    'profile.member_since': 'Manm depi',
    'profile.theme': 'Tèm',
    'profile.language': 'Lang',
    'profile.save': 'Sove',
    'profile.not_set': 'Pa konfigire',

    'common.loading': 'Chajman...',
    'common.error': 'Te gen yon erè',
    'common.back': '← Retounen',
    'common.cancel': 'Anile',
    'common.confirm': 'Konfime',
    'common.save': 'Sove',
    'common.close': 'Fèmen',
    'common.or': 'oswa',
    'common.usd': 'USD',
    'common.status_active': 'Aktif',
    'common.status_pending': 'An atant',
    'common.status_suspended': 'Sispann',
  }
};

export const useAppStore = create<AppState>()(
  persist(
    (set, get) => ({
      theme: 'dark',
      language: 'fr',
      token: null,
      setTheme: (theme) => {
        const root = document.documentElement;
        root.classList.remove('light', 'dark', 'midnight', 'gold');
        if (theme !== 'light') root.classList.add(theme);
        set({ theme });
      },
      setLanguage: (language) => set({ language }),
      setToken: (token) => {
        if (token) localStorage.setItem('ecrossflow_token', token);
        else localStorage.removeItem('ecrossflow_token');
        set({ token });
      },
      logout: () => {
        localStorage.removeItem('ecrossflow_token');
        set({ token: null });
      },
      t: (key) => {
        const lang = get().language;
        return translations[lang][key] || translations['fr'][key] || key;
      }
    }),
    { 
      name: 'ecrossflow-storage',
      partialize: (state) => ({ theme: state.theme, language: state.language, token: state.token }),
    }
  )
);
