import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Theme = 'light' | 'dark' | 'midnight' | 'gold';
export type CoreLanguage = 'fr' | 'en' | 'es' | 'ht';
export type Language = string;

interface AppState {
  theme: Theme;
  language: Language;
  token: string | null;
  remoteMessages: Record<string, string>;
  setTheme: (theme: Theme) => void;
  setLanguage: (lang: Language) => void;
  setRemoteMessages: (messages: Record<string, string>) => void;
  setToken: (token: string | null) => void;
  logout: () => void;
  t: (key: string) => string;
}

const translations: Record<CoreLanguage, Record<string, string>> = {
  fr: {
    'nav.dashboard': 'Tableau de bord',
    'nav.wallet': 'Bourse',
    'nav.boards': 'Boards',
    'nav.how_it_works': 'Comment ça marche',
    'nav.history': 'Historique',
    'nav.referrals': 'Parrainage',
	    'nav.notifications': 'Notifications',
	    'nav.profile': 'Profil',
	    'nav.academy': 'Académie',
	    'nav.admin': 'Admin',
    'nav.logout': 'Déconnexion',

    'wallet.balance': 'Solde Disponible',
    'wallet.pending': 'En attente',
    'wallet.reserved': 'Réservé',
    'wallet.total': 'Total',
    'wallet.deposit': 'Déposer',
    'wallet.withdraw': 'Retirer',
    'wallet.convert': 'Convertir',
    'wallet.method': 'Méthode de paiement',
    'wallet.amount': 'Montant',
    'wallet.currency': 'Devise',
    'wallet.reference': 'Référence',
    'wallet.submit': 'Soumettre',
    'wallet.pending_review': 'En attente de validation',
    'wallet.title': 'Bourse virtuelle',
    'wallet.subtitle': 'Gérez vos fonds via les pages dédiées dépôt/retrait.',
    'wallet.available': 'Disponible',
    'wallet.blocked': 'Bloqué',
    'wallet.deposit_now': 'Déposer maintenant',
    'wallet.deposit_desc': 'NatCash, MonCash, crypto manuel, ou lien de paiement carte configuré par admin.',
    'wallet.open_deposit': 'Ouvrir la page dépôt',
    'wallet.withdraw_fast': 'Retrait rapide',
    'wallet.withdraw_desc': 'Retire tes gains facilement via les méthodes disponibles. Traitement sécurisé selon les réseaux activés.',
    'wallet.withdraw_now': 'Retirer mes fonds',
    'wallet.security_title': 'Traitement contrôlé et sécurisé',
    'wallet.security_desc': 'Chaque transaction fait l’objet d’une vérification avec suivi des références afin d’assurer un traitement fiable et transparent.',

    'deposit.title': 'Dépôt / Recharge',
    'deposit.subtitle': 'Choisis une méthode active et envoie la preuve de paiement.',
    'deposit.instructions': 'Instructions',
    'deposit.processing_eta': 'Temps de traitement estimé',
    'deposit.mobile_money_hint': 'Envoie le montant indiqué via {method} aux informations ci-dessous, puis confirme ton dépôt.',
    'deposit.account_name': 'Nom',
    'deposit.account_number': 'Numéro',
    'deposit.crypto_warning': 'Envoyer uniquement la crypto sélectionnée sur le réseau affiché. Tout autre envoi sera perdu.',
    'deposit.address': 'Adresse',
    'deposit.card_title': 'Payer avec ma carte',
    'deposit.card_text': 'Tu vas être redirigé vers une page sécurisée pour compléter ton paiement.',
    'deposit.card_button': 'Payer maintenant',
    'deposit.card_link_missing': 'Lien carte non configuré par admin.',
    'deposit.reference_label': 'Transaction ID / Référence',
    'deposit.reference_placeholder': 'Ex: MC-8392201',
    'deposit.receipt_label': 'Capture du reçu',
    'deposit.upload_receipt': 'Uploader la capture',
    'deposit.submit': 'Soumettre le dépôt',
    'deposit.success_submitted': 'Dépôt soumis avec succès. En attente de confirmation admin.',
    'deposit.error_load_config': 'Impossible de charger la configuration de paiement',
    'deposit.error_loading': 'Erreur de chargement',
    'deposit.error_invalid_amount': 'Montant invalide.',
    'deposit.error_min_amount': 'Le montant minimum est 2 USD.',
    'deposit.error_reference_required': 'ID transaction requis.',
    'deposit.error_receipt_required': 'Capture du reçu obligatoire.',
    'deposit.error_rejected': 'Dépôt refusé',
    'deposit.error_generic': 'Erreur dépôt',
    'deposit.method.moncash': 'MonCash',
    'deposit.method.natcash': 'NatCash',
    'deposit.method.crypto': 'Crypto',
    'deposit.method.card': 'Carte',

    'withdraw.title': 'Retrait',
    'withdraw.subtitle': 'Sélectionnez la méthode et soumettez votre demande.',
    'withdraw.processing_title': 'Traitement estimé',
    'withdraw.recipient_name': 'Nom destinataire',
    'withdraw.recipient_name_placeholder': 'Nom complet',
    'withdraw.recipient_phone': 'Numéro destinataire',
    'withdraw.recipient_phone_placeholder': 'Ex: +509...',
    'withdraw.crypto_network': 'Réseau crypto',
    'withdraw.destination_address': 'Adresse destination',
    'withdraw.destination_placeholder': '0x...',
    'withdraw.submit': 'Soumettre le retrait',
    'withdraw.success_submitted': 'Demande de retrait envoyée. Traitement manuel en cours.',
    'withdraw.error_load_config': 'Impossible de charger la configuration de paiement',
    'withdraw.error_loading': 'Erreur de chargement',
    'withdraw.error_invalid_amount': 'Montant invalide.',
    'withdraw.error_recipient_required': 'Nom et numéro du destinataire requis.',
    'withdraw.error_destination_required': 'Adresse crypto destination requise.',
    'withdraw.error_crypto_required': 'Sélectionnez un réseau crypto.',
    'withdraw.error_rejected': 'Retrait refusé',
    'withdraw.error_generic': 'Erreur retrait',
    'withdraw.method.moncash': 'MonCash',
    'withdraw.method.natcash': 'NatCash',
    'withdraw.method.crypto': 'Crypto',

	    'dashboard.greeting': 'Bienvenue',
	    'dashboard.title': 'Tableau de bord',
	    'dashboard.welcome_back': 'Bon retour.',
	    'dashboard.welcome_back_named': 'Bon retour, {name}. Avançons ensemble.',
	    'dashboard.balance_title': 'Solde disponible',
	    'dashboard.current_board': 'Board actuel',
	    'dashboard.current_focus': 'Focus actuel',
	    'dashboard.recent_activity': 'Activité récente',
	    'dashboard.recent_gains': 'Gains récents',
	    'dashboard.view_all': 'Voir tout',
	    'dashboard.deposit': 'Déposer',
	    'dashboard.go_boards': 'Voir les Boards',
	    'dashboard.view_pyramid': 'Voir la Pyramide',
	    'dashboard.pending_in_boards': 'En attente (dans les niveaux)',
	    'dashboard.reserved': 'Réservé',
	    'dashboard.total_assets': 'Actifs totaux',
	    'dashboard.level_label': 'Niveau',
	    'dashboard.progress_hint': 'Tu progresses bien. Invite plus de personnes pour accélérer.',
	    'dashboard.view_level_details': 'Voir les détails du niveau',
	    'dashboard.referral_progress': 'Progression parrainage',
	    'dashboard.account_activation': 'Activation du compte',
	    'dashboard.bonus_eligibility': 'Éligibilité bonus',
	    'dashboard.first_referral_unlock': 'Gains parrainage dès 1 filleul actif. Progression board suivant: 2 filleuls actifs minimum.',
	    'dashboard.your_code': 'Ton code',
	    'dashboard.root_owner': 'Propriétaire racine',
	    'dashboard.position': 'Position',
    'dashboard.join_starter': 'Rejoindre le Board de départ',
    'dashboard.not_in_board': 'Pas encore dans un board actif.',
    'dashboard.no_recent_gains': 'Aucun gain récent',
    'dashboard.no_activity': 'Aucune activité récente.',
    'dashboard.na': 'N/A',

    'boards.title': 'Pyramid Boards',
    'boards.subtitle': '7 niveaux progressifs — de F à S',
    'boards.select': 'Sélectionner',
    'boards.pay': 'Payer la cotisation',
    'boards.fee': 'Cotisation',
    'boards.gain': 'Gain total',
    'boards.members': 'membres',
    'boards.join': 'Rejoindre ce Board',
    'boards.insufficient': 'Solde insuffisant',
    'boards.already_in': 'Déjà membre',
    'boards.completed': 'Complété',
    'boards.pending': 'En attente',
    'boards.page_title': 'CREATION BOARDS',
    'boards.page_subtitle': '7 niveaux progressifs de F à S',
    'boards.level': 'Niveau',
    'boards.board_label': 'Board',
    'boards.entry_cost': 'Coût d’entrée',
    'boards.current_progress': 'Progression actuelle',
    'boards.step': 'Étape',
    'boards.not_active': 'Non actif',
    'boards.position': 'Position',
    'boards.step_progression': 'Progression des étapes pour',
    'boards.already_activated': 'Ton niveau est déjà activé.',
    'boards.auto_activation_notice': 'Ce niveau est activé automatiquement par progression après la complétion du Board F.',
    'boards.insufficient_notice': 'Solde insuffisant. Dépose au moins ${amount} pour activer ce niveau.',
    'boards.processing': 'Traitement...',
    'boards.activate_level': 'Activer ce niveau',
    'boards.activation_cost': 'Coût d’activation',
    'boards.wallet_balance': 'Solde bourse',
    'boards.loading_levels': 'Chargement des niveaux...',
    'boards.step.starter': 'Starter',
    'boards.step.challenger': 'Challenger',
    'boards.step.leader': 'Leader',
    'boards.step.ranker': 'Ranker',
    'boards.theme.f': 'Foundation',
    'boards.theme.e': 'Expansion',
    'boards.theme.d': 'Development',
    'boards.theme.c': 'Consolidation',
    'boards.theme.b': 'Breakthrough',
    'boards.theme.a': 'Ascension',
    'boards.theme.s': 'Summit',

    'auth.login': 'Connexion',
    'auth.register': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.username': 'Nom d\'utilisateur',
    'auth.first_name': 'Prénom',
    'auth.last_name': 'Nom',
    'auth.referral_code': 'Code de parrainage (obligatoire)',
    'auth.forgot_password': 'Mot de passe oublié ?',
    'auth.no_account': 'Pas encore de compte ?',
    'auth.have_account': 'Déjà un compte ?',
    'auth.sign_in': 'Se connecter',
    'auth.create_account': 'Créer un compte',
    'auth.register_now': 'S\'inscrire maintenant',
    'auth.login_instead': 'Se connecter',

    'verify.title': 'Vérifiez votre email',
    'verify.subtitle': 'Un code de vérification a été envoyé à',
    'verify.enter_code': 'Entrez le code à 6 chiffres',
    'verify.resend': 'Renvoyer le code',
    'verify.resend_in': 'Renvoyer dans',
    'verify.verify': 'Vérifier',
    'verify.back': 'Retour à la connexion',

    'onboarding.step1': 'Choisissez votre langue',
    'onboarding.step2': 'Choisissez votre thème',
    'onboarding.step3': 'Configurez votre profil',
    'onboarding.step4': 'Votre code de parrainage',
    'onboarding.continue': 'Continuer',
    'onboarding.finish': 'Terminer l\'installation',
    'onboarding.welcome': 'Bienvenue sur Ecrossflow',
    'onboarding.step_of': 'Étape',
    'onboarding.of': 'sur',

    'history.title': 'Historique',
    'history.subtitle': 'Toutes vos transactions',
    'history.all': 'Toutes',
    'history.deposit': 'Dépôt',
    'history.withdrawal': 'Retrait',
    'history.board_payment': 'Paiement Board',
    'history.board_receipt': 'Gain Board',
    'history.referral_bonus': 'Bonus Parrainage',
    'history.system_fee': 'Frais Système',
    'history.no_transactions': 'Aucune transaction trouvée',
    'history.previous': '← Précédent',
    'history.next': 'Suivant →',
    'history.page': 'Page',
    'history.report': 'Rapport',
    'history.export_csv': 'Export CSV',
    'history.filters': 'Filtres',
    'history.status': 'Statut',
    'history.payment_method': 'Méthode de paiement',
    'history.date_from': 'Date début',
    'history.date_to': 'Date fin',
    'history.amount_min': 'Montant min (USD)',
    'history.amount_max': 'Montant max (USD)',
    'history.reset_filters': 'Réinitialiser les filtres',
    'history.adjust_filters': 'Essayez de modifier vos filtres',
    'history.status_completed': 'Complété',
    'history.status_pending': 'En attente',
    'history.status_processing': 'En traitement',
    'history.status_cancelled': 'Annulé',
    'history.view_report': 'Voir le rapport détaillé',

    'referrals.title': 'Parrainage',
    'referrals.subtitle': 'Invitez vos amis et gagnez des bonus',
    'referrals.your_code': 'Votre code de parrainage',
    'referrals.copy_code': 'Copier le code',
    'referrals.copy_link': 'Copier le lien',
    'referrals.copied': 'Copié !',
    'referrals.total': 'Total filleuls',
    'referrals.active': 'Filleuls actifs',
    'referrals.bonus': 'Bonus total',
    'referrals.no_referrals': 'Aucun filleul pour l\'instant',
    'referrals.share': 'Partagez votre code pour commencer !',
    'referrals.activation_title': 'Activation du compte parrainage',
    'referrals.activation_done': 'Votre programme de parrainage est activé !',
    'referrals.activation_needed': '{current}/{required} filleuls actifs requis pour activer les bonus',
    'referrals.activation_left': 'Encore {left} filleul(s) actif(s) pour débloquer les bonus de parrainage.',
    'referrals.qr_show': 'Afficher QR Code',
    'referrals.share_hint': 'Partagez ce lien ou ce code. Vous recevrez un bonus lorsque vos filleuls rejoignent leur premier board.',
    'referrals.list_title': 'Vos filleuls',
    'referrals.joined_on': 'Rejoint le',
    'referrals.bonus_paid': 'Bonus payé',

    'notifications.title': 'Notifications',
    'notifications.all': 'Toutes',
    'notifications.unread': 'Non lues',
    'notifications.financial': 'Finance',
    'notifications.security': 'Sécurité',
    'notifications.mark_all': 'Tout marquer lu',
    'notifications.none': 'Aucune notification',
    'notifications.unread_count': 'non lue(s)',
    'notifications.loaded_all': 'Toutes les notifications chargées',

    'profile.title': 'Profil',
    'profile.subtitle': 'Vos informations et préférences',
    'profile.account_number': 'Numéro de compte',
    'profile.email': 'Email',
    'profile.phone': 'Téléphone',
    'profile.current_board': 'Board actuel',
    'profile.referral_code': 'Code de parrainage',
    'profile.member_since': 'Membre depuis',
    'profile.theme': 'Thème',
    'profile.language': 'Langue',
    'profile.save': 'Sauvegarder',
    'profile.not_set': 'Non renseigné',

    'common.loading': 'Chargement...',
    'common.error': 'Une erreur est survenue',
    'common.back': '← Retour',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.save': 'Sauvegarder',
    'common.close': 'Fermer',
    'common.or': 'ou',
    'common.usd': 'USD',
    'common.status_active': 'Actif',
    'common.status_pending': 'En attente',
    'common.status_suspended': 'Suspendu',
  },
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.wallet': 'Wallet',
    'nav.boards': 'Boards',
    'nav.how_it_works': 'How it Works',
    'nav.history': 'History',
    'nav.referrals': 'Referrals',
	    'nav.notifications': 'Notifications',
	    'nav.profile': 'Profile',
	    'nav.academy': 'Academy',
	    'nav.admin': 'Admin',
    'nav.logout': 'Logout',

    'wallet.balance': 'Available Balance',
    'wallet.pending': 'Pending',
    'wallet.reserved': 'Reserved',
    'wallet.total': 'Total',
    'wallet.deposit': 'Deposit',
    'wallet.withdraw': 'Withdraw',
    'wallet.convert': 'Convert',
    'wallet.method': 'Payment method',
    'wallet.amount': 'Amount',
    'wallet.currency': 'Currency',
    'wallet.reference': 'Reference',
    'wallet.submit': 'Submit',
    'wallet.pending_review': 'Pending review',
    'wallet.title': 'Virtual Wallet',
    'wallet.subtitle': 'Manage your funds from the dedicated deposit/withdraw pages.',
    'wallet.available': 'Available',
    'wallet.blocked': 'Blocked',
    'wallet.deposit_now': 'Deposit now',
    'wallet.deposit_desc': 'NatCash, MonCash, manual crypto, or card payment link configured by admin.',
    'wallet.open_deposit': 'Open deposit page',
    'wallet.withdraw_fast': 'Fast withdrawal',
    'wallet.withdraw_desc': 'Withdraw your earnings easily via available methods. Secure processing based on enabled networks.',
    'wallet.withdraw_now': 'Withdraw my funds',
    'wallet.security_title': 'Controlled and secure processing',
    'wallet.security_desc': 'Each transaction is verified with reference tracking to ensure reliable and transparent processing.',

    'deposit.title': 'Deposit / Top up',
    'deposit.subtitle': 'Choose an active method and submit your payment proof.',
    'deposit.instructions': 'Instructions',
    'deposit.processing_eta': 'Estimated processing time',
    'deposit.mobile_money_hint': 'Send the required amount via {method} to the details below, then confirm your deposit.',
    'deposit.account_name': 'Name',
    'deposit.account_number': 'Number',
    'deposit.crypto_warning': 'Send only the selected crypto on the displayed network. Any other transfer will be lost.',
    'deposit.address': 'Address',
    'deposit.card_title': 'Pay with my card',
    'deposit.card_text': 'You will be redirected to a secure page to complete your payment.',
    'deposit.card_button': 'Pay now',
    'deposit.card_link_missing': 'Card link not configured by admin.',
    'deposit.reference_label': 'Transaction ID / Reference',
    'deposit.reference_placeholder': 'Ex: MC-8392201',
    'deposit.receipt_label': 'Receipt screenshot',
    'deposit.upload_receipt': 'Upload screenshot',
    'deposit.submit': 'Submit deposit',
    'deposit.success_submitted': 'Deposit submitted successfully. Waiting for admin confirmation.',
    'deposit.error_load_config': 'Unable to load payment configuration',
    'deposit.error_loading': 'Loading error',
    'deposit.error_invalid_amount': 'Invalid amount.',
    'deposit.error_min_amount': 'Minimum amount is 2 USD.',
    'deposit.error_reference_required': 'Transaction ID is required.',
    'deposit.error_receipt_required': 'Receipt screenshot is required.',
    'deposit.error_rejected': 'Deposit rejected',
    'deposit.error_generic': 'Deposit error',
    'deposit.method.moncash': 'MonCash',
    'deposit.method.natcash': 'NatCash',
    'deposit.method.crypto': 'Crypto',
    'deposit.method.card': 'Card',

    'withdraw.title': 'Withdraw',
    'withdraw.subtitle': 'Select the method and submit your request.',
    'withdraw.processing_title': 'Estimated processing',
    'withdraw.recipient_name': 'Recipient name',
    'withdraw.recipient_name_placeholder': 'Full name',
    'withdraw.recipient_phone': 'Recipient number',
    'withdraw.recipient_phone_placeholder': 'Ex: +509...',
    'withdraw.crypto_network': 'Crypto network',
    'withdraw.destination_address': 'Destination address',
    'withdraw.destination_placeholder': '0x...',
    'withdraw.submit': 'Submit withdrawal',
    'withdraw.success_submitted': 'Withdrawal request sent. Manual processing in progress.',
    'withdraw.error_load_config': 'Unable to load payment configuration',
    'withdraw.error_loading': 'Loading error',
    'withdraw.error_invalid_amount': 'Invalid amount.',
    'withdraw.error_recipient_required': 'Recipient name and number are required.',
    'withdraw.error_destination_required': 'Destination crypto address is required.',
    'withdraw.error_crypto_required': 'Select a crypto network.',
    'withdraw.error_rejected': 'Withdrawal rejected',
    'withdraw.error_generic': 'Withdrawal error',
    'withdraw.method.moncash': 'MonCash',
    'withdraw.method.natcash': 'NatCash',
    'withdraw.method.crypto': 'Crypto',

	    'dashboard.greeting': 'Welcome',
	    'dashboard.title': 'Dashboard',
	    'dashboard.welcome_back': 'Welcome back.',
	    'dashboard.welcome_back_named': 'Welcome back, {name}. Let\'s grow together.',
	    'dashboard.balance_title': 'Available balance',
	    'dashboard.current_board': 'Current board',
	    'dashboard.current_focus': 'Current focus',
	    'dashboard.recent_activity': 'Recent activity',
	    'dashboard.recent_gains': 'Recent gains',
	    'dashboard.view_all': 'View all',
	    'dashboard.deposit': 'Deposit',
	    'dashboard.go_boards': 'Go to Boards',
	    'dashboard.view_pyramid': 'View Pyramid',
	    'dashboard.pending_in_boards': 'Pending (in levels)',
	    'dashboard.reserved': 'Reserved',
	    'dashboard.total_assets': 'Total assets',
	    'dashboard.level_label': 'Level',
	    'dashboard.progress_hint': 'You are progressing well. Invite more people to accelerate.',
	    'dashboard.view_level_details': 'View level details',
	    'dashboard.referral_progress': 'Referral progress',
	    'dashboard.account_activation': 'Account activation',
	    'dashboard.bonus_eligibility': 'Bonus eligibility',
	    'dashboard.first_referral_unlock': 'Referral earnings unlock from your first active referral. Next board progression requires at least 2 active referrals.',
	    'dashboard.your_code': 'Your code',
	    'dashboard.root_owner': 'Root owner',
	    'dashboard.position': 'Position',
	    'dashboard.join_starter': 'Join Starter Board',
	    'dashboard.not_in_board': 'Not in any active board.',
	    'dashboard.no_recent_gains': 'No recent gains yet',
	    'dashboard.no_activity': 'No recent activity.',
      'dashboard.na': 'N/A',

    'boards.title': 'Pyramid Boards',
    'boards.subtitle': '7 progressive levels — F to S',
    'boards.select': 'Select',
    'boards.pay': 'Pay entry fee',
    'boards.fee': 'Entry fee',
    'boards.gain': 'Total gain',
    'boards.members': 'members',
    'boards.join': 'Join this Board',
    'boards.insufficient': 'Insufficient balance',
    'boards.already_in': 'Already a member',
    'boards.completed': 'Completed',
    'boards.pending': 'Pending',
    'boards.page_title': 'CREATION BOARDS',
    'boards.page_subtitle': '7 progressive levels from F to S',
    'boards.level': 'Level',
    'boards.board_label': 'Board',
    'boards.entry_cost': 'Entry cost',
    'boards.current_progress': 'Current progress',
    'boards.step': 'Step',
    'boards.not_active': 'Not active',
    'boards.position': 'Position',
    'boards.step_progression': 'Step progression for',
    'boards.already_activated': 'Your level is already activated.',
    'boards.auto_activation_notice': 'This level is activated automatically by progression after Board F completion.',
    'boards.insufficient_notice': 'Insufficient balance. Deposit at least ${amount} to activate this level.',
    'boards.processing': 'Processing...',
    'boards.activate_level': 'Activate this level',
    'boards.activation_cost': 'Activation cost',
    'boards.wallet_balance': 'Wallet balance',
    'boards.loading_levels': 'Loading levels...',
    'boards.step.starter': 'Starter',
    'boards.step.challenger': 'Challenger',
    'boards.step.leader': 'Leader',
    'boards.step.ranker': 'Ranker',
    'boards.theme.f': 'Foundation',
    'boards.theme.e': 'Expansion',
    'boards.theme.d': 'Development',
    'boards.theme.c': 'Consolidation',
    'boards.theme.b': 'Breakthrough',
    'boards.theme.a': 'Ascension',
    'boards.theme.s': 'Summit',

    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.username': 'Username',
    'auth.first_name': 'First name',
    'auth.last_name': 'Last name',
    'auth.referral_code': 'Referral code (required)',
    'auth.forgot_password': 'Forgot password?',
    'auth.no_account': 'Don\'t have an account?',
    'auth.have_account': 'Already have an account?',
    'auth.sign_in': 'Sign in',
    'auth.create_account': 'Create account',
    'auth.register_now': 'Register now',
    'auth.login_instead': 'Log in instead',

    'verify.title': 'Verify your email',
    'verify.subtitle': 'A verification code was sent to',
    'verify.enter_code': 'Enter the 6-digit code',
    'verify.resend': 'Resend code',
    'verify.resend_in': 'Resend in',
    'verify.verify': 'Verify',
    'verify.back': 'Back to login',

    'onboarding.step1': 'Choose your language',
    'onboarding.step2': 'Choose your theme',
    'onboarding.step3': 'Set up your profile',
    'onboarding.step4': 'Your referral code',
    'onboarding.continue': 'Continue',
    'onboarding.finish': 'Finish setup',
    'onboarding.welcome': 'Welcome to Ecrossflow',
    'onboarding.step_of': 'Step',
    'onboarding.of': 'of',

    'history.title': 'History',
    'history.subtitle': 'All your transactions',
    'history.all': 'All',
    'history.deposit': 'Deposit',
    'history.withdrawal': 'Withdrawal',
    'history.board_payment': 'Board Payment',
    'history.board_receipt': 'Board Receipt',
    'history.referral_bonus': 'Referral Bonus',
    'history.system_fee': 'System Fee',
    'history.no_transactions': 'No transactions found',
    'history.previous': '← Previous',
    'history.next': 'Next →',
    'history.page': 'Page',
    'history.report': 'Report',
    'history.export_csv': 'Export CSV',
    'history.filters': 'Filters',
    'history.status': 'Status',
    'history.payment_method': 'Payment method',
    'history.date_from': 'Start date',
    'history.date_to': 'End date',
    'history.amount_min': 'Min amount (USD)',
    'history.amount_max': 'Max amount (USD)',
    'history.reset_filters': 'Reset filters',
    'history.adjust_filters': 'Try changing your filters',
    'history.status_completed': 'Completed',
    'history.status_pending': 'Pending',
    'history.status_processing': 'Processing',
    'history.status_cancelled': 'Cancelled',
    'history.view_report': 'View detailed report',

    'referrals.title': 'Referrals',
    'referrals.subtitle': 'Invite friends and earn bonuses',
    'referrals.your_code': 'Your referral code',
    'referrals.copy_code': 'Copy code',
    'referrals.copy_link': 'Copy link',
    'referrals.copied': 'Copied!',
    'referrals.total': 'Total referrals',
    'referrals.active': 'Active referrals',
    'referrals.bonus': 'Total bonus',
    'referrals.no_referrals': 'No referrals yet',
    'referrals.share': 'Share your code to get started!',
    'referrals.activation_title': 'Referral account activation',
    'referrals.activation_done': 'Your referral program is activated!',
    'referrals.activation_needed': '{current}/{required} active referrals required to unlock bonuses',
    'referrals.activation_left': '{left} active referral(s) left to unlock referral bonuses.',
    'referrals.qr_show': 'Show QR Code',
    'referrals.share_hint': 'Share this link or code. You will receive a bonus when your referrals join their first board.',
    'referrals.list_title': 'Your referrals',
    'referrals.joined_on': 'Joined on',
    'referrals.bonus_paid': 'Bonus paid',

    'notifications.title': 'Notifications',
    'notifications.all': 'All',
    'notifications.unread': 'Unread',
    'notifications.financial': 'Financial',
    'notifications.security': 'Security',
    'notifications.mark_all': 'Mark all as read',
    'notifications.none': 'No notifications',
    'notifications.unread_count': 'unread',
    'notifications.loaded_all': 'All notifications loaded',

    'profile.title': 'Profile',
    'profile.subtitle': 'Your information and preferences',
    'profile.account_number': 'Account number',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.current_board': 'Current board',
    'profile.referral_code': 'Referral code',
    'profile.member_since': 'Member since',
    'profile.theme': 'Theme',
    'profile.language': 'Language',
    'profile.save': 'Save',
    'profile.not_set': 'Not set',

    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.back': '← Back',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.close': 'Close',
    'common.or': 'or',
    'common.usd': 'USD',
    'common.status_active': 'Active',
    'common.status_pending': 'Pending',
    'common.status_suspended': 'Suspended',
  },
  es: {
    'nav.dashboard': 'Panel',
    'nav.wallet': 'Billetera',
    'nav.boards': 'Tableros',
    'nav.how_it_works': 'Cómo funciona',
    'nav.history': 'Historial',
    'nav.referrals': 'Referidos',
	    'nav.notifications': 'Notificaciones',
	    'nav.profile': 'Perfil',
	    'nav.academy': 'Academia',
	    'nav.admin': 'Admin',
    'nav.logout': 'Salir',

    'wallet.balance': 'Saldo Disponible',
    'wallet.pending': 'Pendiente',
    'wallet.reserved': 'Reservado',
    'wallet.total': 'Total',
    'wallet.deposit': 'Depositar',
    'wallet.withdraw': 'Retirar',
    'wallet.convert': 'Convertir',
    'wallet.method': 'Método de pago',
    'wallet.amount': 'Monto',
    'wallet.currency': 'Divisa',
    'wallet.reference': 'Referencia',
    'wallet.submit': 'Enviar',
    'wallet.pending_review': 'En revisión',
    'wallet.title': 'Billetera virtual',
    'wallet.subtitle': 'Gestiona tus fondos desde las páginas de depósito/retiro.',
    'wallet.available': 'Disponible',
    'wallet.blocked': 'Bloqueado',
    'wallet.deposit_now': 'Depositar ahora',
    'wallet.deposit_desc': 'NatCash, MonCash, cripto manual o enlace de pago con tarjeta configurado por admin.',
    'wallet.open_deposit': 'Abrir página de depósito',
    'wallet.withdraw_fast': 'Retiro rápido',
    'wallet.withdraw_desc': 'Retira tus ganancias fácilmente con los métodos disponibles. Procesamiento seguro según redes activas.',
    'wallet.withdraw_now': 'Retirar mis fondos',
    'wallet.security_title': 'Procesamiento controlado y seguro',
    'wallet.security_desc': 'Cada transacción se verifica con seguimiento de referencias para asegurar un tratamiento fiable y transparente.',

    'deposit.title': 'Depósito / Recarga',
    'deposit.subtitle': 'Elige un método activo y envía tu comprobante de pago.',
    'deposit.instructions': 'Instrucciones',
    'deposit.processing_eta': 'Tiempo de procesamiento estimado',
    'deposit.mobile_money_hint': 'Envía el monto indicado vía {method} a los datos siguientes y luego confirma tu depósito.',
    'deposit.account_name': 'Nombre',
    'deposit.account_number': 'Número',
    'deposit.crypto_warning': 'Envía solo la cripto seleccionada en la red mostrada. Cualquier otro envío se perderá.',
    'deposit.address': 'Dirección',
    'deposit.card_title': 'Pagar con mi tarjeta',
    'deposit.card_text': 'Serás redirigido a una página segura para completar tu pago.',
    'deposit.card_button': 'Pagar ahora',
    'deposit.card_link_missing': 'Enlace de tarjeta no configurado por admin.',
    'deposit.reference_label': 'ID de transacción / Referencia',
    'deposit.reference_placeholder': 'Ej: MC-8392201',
    'deposit.receipt_label': 'Captura del recibo',
    'deposit.upload_receipt': 'Subir captura',
    'deposit.submit': 'Enviar depósito',
    'deposit.success_submitted': 'Depósito enviado con éxito. En espera de confirmación admin.',
    'deposit.error_load_config': 'No se pudo cargar la configuración de pago',
    'deposit.error_loading': 'Error de carga',
    'deposit.error_invalid_amount': 'Monto inválido.',
    'deposit.error_min_amount': 'El monto mínimo es 2 USD.',
    'deposit.error_reference_required': 'ID de transacción obligatorio.',
    'deposit.error_receipt_required': 'La captura del recibo es obligatoria.',
    'deposit.error_rejected': 'Depósito rechazado',
    'deposit.error_generic': 'Error de depósito',
    'deposit.method.moncash': 'MonCash',
    'deposit.method.natcash': 'NatCash',
    'deposit.method.crypto': 'Cripto',
    'deposit.method.card': 'Tarjeta',

    'withdraw.title': 'Retiro',
    'withdraw.subtitle': 'Selecciona el método y envía tu solicitud.',
    'withdraw.processing_title': 'Procesamiento estimado',
    'withdraw.recipient_name': 'Nombre del destinatario',
    'withdraw.recipient_name_placeholder': 'Nombre completo',
    'withdraw.recipient_phone': 'Número del destinatario',
    'withdraw.recipient_phone_placeholder': 'Ej: +509...',
    'withdraw.crypto_network': 'Red cripto',
    'withdraw.destination_address': 'Dirección destino',
    'withdraw.destination_placeholder': '0x...',
    'withdraw.submit': 'Enviar retiro',
    'withdraw.success_submitted': 'Solicitud de retiro enviada. Procesamiento manual en curso.',
    'withdraw.error_load_config': 'No se pudo cargar la configuración de pago',
    'withdraw.error_loading': 'Error de carga',
    'withdraw.error_invalid_amount': 'Monto inválido.',
    'withdraw.error_recipient_required': 'Nombre y número del destinatario obligatorios.',
    'withdraw.error_destination_required': 'Dirección cripto de destino obligatoria.',
    'withdraw.error_crypto_required': 'Selecciona una red cripto.',
    'withdraw.error_rejected': 'Retiro rechazado',
    'withdraw.error_generic': 'Error de retiro',
    'withdraw.method.moncash': 'MonCash',
    'withdraw.method.natcash': 'NatCash',
    'withdraw.method.crypto': 'Cripto',

	    'dashboard.greeting': 'Bienvenido',
	    'dashboard.title': 'Panel',
	    'dashboard.welcome_back': 'Bienvenido de nuevo.',
	    'dashboard.welcome_back_named': 'Bienvenido de nuevo, {name}. Avancemos juntos.',
	    'dashboard.balance_title': 'Saldo disponible',
	    'dashboard.current_board': 'Tablero actual',
	    'dashboard.current_focus': 'Enfoque actual',
	    'dashboard.recent_activity': 'Actividad reciente',
	    'dashboard.recent_gains': 'Ganancias recientes',
	    'dashboard.view_all': 'Ver todo',
	    'dashboard.deposit': 'Depositar',
	    'dashboard.go_boards': 'Ir a Tableros',
	    'dashboard.view_pyramid': 'Ver Pirámide',
	    'dashboard.pending_in_boards': 'Pendiente (en niveles)',
	    'dashboard.reserved': 'Reservado',
	    'dashboard.total_assets': 'Activos totales',
	    'dashboard.level_label': 'Nivel',
	    'dashboard.progress_hint': 'Vas progresando bien. Invita a más personas para acelerar.',
	    'dashboard.view_level_details': 'Ver detalles del nivel',
	    'dashboard.referral_progress': 'Progreso de referidos',
	    'dashboard.account_activation': 'Activación de cuenta',
	    'dashboard.bonus_eligibility': 'Elegibilidad de bono',
	    'dashboard.first_referral_unlock': 'Las ganancias por referidos se desbloquean desde tu primer referido activo. La progresión al siguiente board requiere al menos 2 referidos activos.',
	    'dashboard.your_code': 'Tu código',
	    'dashboard.root_owner': 'Propietario raíz',
	    'dashboard.position': 'Posición',
	    'dashboard.join_starter': 'Unirse al Tablero inicial',
	    'dashboard.not_in_board': 'No estás en ningún tablero activo.',
	    'dashboard.no_recent_gains': 'Sin ganancias recientes',
	    'dashboard.no_activity': 'Sin actividad reciente.',
      'dashboard.na': 'N/A',

    'boards.title': 'Tableros Pirámide',
    'boards.subtitle': '7 niveles progresivos — de F a S',
    'boards.select': 'Seleccionar',
    'boards.pay': 'Pagar cuota',
    'boards.fee': 'Cuota de entrada',
    'boards.gain': 'Ganancia total',
    'boards.members': 'miembros',
    'boards.join': 'Unirse a este Tablero',
    'boards.insufficient': 'Saldo insuficiente',
    'boards.already_in': 'Ya eres miembro',
    'boards.completed': 'Completado',
    'boards.pending': 'Pendiente',
    'boards.page_title': 'CREATION BOARDS',
    'boards.page_subtitle': '7 niveles progresivos de F a S',
    'boards.level': 'Nivel',
    'boards.board_label': 'Board',
    'boards.entry_cost': 'Costo de entrada',
    'boards.current_progress': 'Progreso actual',
    'boards.step': 'Etapa',
    'boards.not_active': 'No activo',
    'boards.position': 'Posición',
    'boards.step_progression': 'Progresión de etapas para',
    'boards.already_activated': 'Tu nivel ya está activado.',
    'boards.auto_activation_notice': 'Este nivel se activa automáticamente por progresión después de completar el Board F.',
    'boards.insufficient_notice': 'Saldo insuficiente. Deposita al menos ${amount} para activar este nivel.',
    'boards.processing': 'Procesando...',
    'boards.activate_level': 'Activar este nivel',
    'boards.activation_cost': 'Costo de activación',
    'boards.wallet_balance': 'Saldo de billetera',
    'boards.loading_levels': 'Cargando niveles...',
    'boards.step.starter': 'Starter',
    'boards.step.challenger': 'Challenger',
    'boards.step.leader': 'Leader',
    'boards.step.ranker': 'Ranker',
    'boards.theme.f': 'Foundation',
    'boards.theme.e': 'Expansion',
    'boards.theme.d': 'Development',
    'boards.theme.c': 'Consolidation',
    'boards.theme.b': 'Breakthrough',
    'boards.theme.a': 'Ascension',
    'boards.theme.s': 'Summit',

    'auth.login': 'Iniciar sesión',
    'auth.register': 'Registrarse',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.username': 'Nombre de usuario',
    'auth.first_name': 'Nombre',
    'auth.last_name': 'Apellido',
    'auth.referral_code': 'Código de referido (obligatorio)',
    'auth.forgot_password': '¿Olvidaste tu contraseña?',
    'auth.no_account': '¿No tienes cuenta?',
    'auth.have_account': '¿Ya tienes cuenta?',
    'auth.sign_in': 'Iniciar sesión',
    'auth.create_account': 'Crear cuenta',
    'auth.register_now': 'Registrarse ahora',
    'auth.login_instead': 'Iniciar sesión',

    'verify.title': 'Verifica tu correo',
    'verify.subtitle': 'Se envió un código de verificación a',
    'verify.enter_code': 'Ingresa el código de 6 dígitos',
    'verify.resend': 'Reenviar código',
    'verify.resend_in': 'Reenviar en',
    'verify.verify': 'Verificar',
    'verify.back': 'Volver al inicio',

    'onboarding.step1': 'Elige tu idioma',
    'onboarding.step2': 'Elige tu tema',
    'onboarding.step3': 'Configura tu perfil',
    'onboarding.step4': 'Tu código de referido',
    'onboarding.continue': 'Continuar',
    'onboarding.finish': 'Finalizar configuración',
    'onboarding.welcome': 'Bienvenido a Ecrossflow',
    'onboarding.step_of': 'Paso',
    'onboarding.of': 'de',

    'history.title': 'Historial',
    'history.subtitle': 'Todas tus transacciones',
    'history.all': 'Todas',
    'history.deposit': 'Depósito',
    'history.withdrawal': 'Retiro',
    'history.board_payment': 'Pago de Tablero',
    'history.board_receipt': 'Recibo de Tablero',
    'history.referral_bonus': 'Bono de Referido',
    'history.system_fee': 'Tarifa del Sistema',
    'history.no_transactions': 'No se encontraron transacciones',
    'history.previous': '← Anterior',
    'history.next': 'Siguiente →',
    'history.page': 'Página',
    'history.report': 'Informe',
    'history.export_csv': 'Exportar CSV',
    'history.filters': 'Filtros',
    'history.status': 'Estado',
    'history.payment_method': 'Método de pago',
    'history.date_from': 'Fecha inicio',
    'history.date_to': 'Fecha fin',
    'history.amount_min': 'Monto mín (USD)',
    'history.amount_max': 'Monto máx (USD)',
    'history.reset_filters': 'Restablecer filtros',
    'history.adjust_filters': 'Intenta cambiar tus filtros',
    'history.status_completed': 'Completado',
    'history.status_pending': 'Pendiente',
    'history.status_processing': 'En proceso',
    'history.status_cancelled': 'Cancelado',
    'history.view_report': 'Ver informe detallado',

    'referrals.title': 'Referidos',
    'referrals.subtitle': 'Invita amigos y gana bonos',
    'referrals.your_code': 'Tu código de referido',
    'referrals.copy_code': 'Copiar código',
    'referrals.copy_link': 'Copiar enlace',
    'referrals.copied': '¡Copiado!',
    'referrals.total': 'Total referidos',
    'referrals.active': 'Referidos activos',
    'referrals.bonus': 'Bono total',
    'referrals.no_referrals': 'Aún no tienes referidos',
    'referrals.share': '¡Comparte tu código para comenzar!',
    'referrals.activation_title': 'Activación de cuenta de referidos',
    'referrals.activation_done': '¡Tu programa de referidos está activado!',
    'referrals.activation_needed': '{current}/{required} referidos activos requeridos para activar bonos',
    'referrals.activation_left': 'Faltan {left} referido(s) activo(s) para desbloquear los bonos.',
    'referrals.qr_show': 'Mostrar código QR',
    'referrals.share_hint': 'Comparte este enlace o código. Recibirás un bono cuando tus referidos entren a su primer board.',
    'referrals.list_title': 'Tus referidos',
    'referrals.joined_on': 'Se unió el',
    'referrals.bonus_paid': 'Bono pagado',

    'notifications.title': 'Notificaciones',
    'notifications.all': 'Todas',
    'notifications.unread': 'No leídas',
    'notifications.financial': 'Financiero',
    'notifications.security': 'Seguridad',
    'notifications.mark_all': 'Marcar todo como leído',
    'notifications.none': 'Sin notificaciones',
    'notifications.unread_count': 'sin leer',
    'notifications.loaded_all': 'Todas las notificaciones cargadas',

    'profile.title': 'Perfil',
    'profile.subtitle': 'Tu información y preferencias',
    'profile.account_number': 'Número de cuenta',
    'profile.email': 'Correo',
    'profile.phone': 'Teléfono',
    'profile.current_board': 'Tablero actual',
    'profile.referral_code': 'Código de referido',
    'profile.member_since': 'Miembro desde',
    'profile.theme': 'Tema',
    'profile.language': 'Idioma',
    'profile.save': 'Guardar',
    'profile.not_set': 'No configurado',

    'common.loading': 'Cargando...',
    'common.error': 'Ocurrió un error',
    'common.back': '← Atrás',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Guardar',
    'common.close': 'Cerrar',
    'common.or': 'o',
    'common.usd': 'USD',
    'common.status_active': 'Activo',
    'common.status_pending': 'Pendiente',
    'common.status_suspended': 'Suspendido',
  },
  ht: {
    'nav.dashboard': 'Dachbòd',
    'nav.wallet': 'Bous',
    'nav.boards': 'Bòd yo',
    'nav.how_it_works': 'Kijan sa travay',
    'nav.history': 'Istwa',
    'nav.referrals': 'Parennaj',
	    'nav.notifications': 'Notifikasyon',
	    'nav.profile': 'Pwofil',
	    'nav.academy': 'Akadèmi',
	    'nav.admin': 'Admin',
    'nav.logout': 'Dekonekte',

    'wallet.balance': 'Balans ki disponib',
    'wallet.pending': 'An atant',
    'wallet.reserved': 'Rezève',
    'wallet.total': 'Total',
    'wallet.deposit': 'Depoze',
    'wallet.withdraw': 'Retire',
    'wallet.convert': 'Konvèti',
    'wallet.method': 'Metòd pèman',
    'wallet.amount': 'Montan',
    'wallet.currency': 'Devis',
    'wallet.reference': 'Referans',
    'wallet.submit': 'Voye',
    'wallet.pending_review': 'An atant verifikasyon',
    'wallet.title': 'Bous vityèl',
    'wallet.subtitle': 'Jere lajan ou sou paj depo/retrè yo.',
    'wallet.available': 'Disponib',
    'wallet.blocked': 'Bloke',
    'wallet.deposit_now': 'Depoze kounye a',
    'wallet.deposit_desc': 'NatCash, MonCash, kripto manyèl, oswa lyen kat admin mete.',
    'wallet.open_deposit': 'Louvri paj depo',
    'wallet.withdraw_fast': 'Retrè rapid',
    'wallet.withdraw_desc': 'Retire benefis ou fasil ak metòd ki disponib yo. Tretman sekirize selon rezo aktif yo.',
    'wallet.withdraw_now': 'Retire fon mwen yo',
    'wallet.security_title': 'Tretman kontwole ak sekirize',
    'wallet.security_desc': 'Chak tranzaksyon verifye ak swivi referans pou asire yon tretman fyab ak transparan.',

    'deposit.title': 'Depo / Rechaj',
    'deposit.subtitle': 'Chwazi yon metòd aktif epi voye prèv peman an.',
    'deposit.instructions': 'Enstriksyon',
    'deposit.processing_eta': 'Tan tretman estime',
    'deposit.mobile_money_hint': 'Voye montan ki mande a pa {method} sou enfòmasyon ki anba yo, apre sa konfime depo a.',
    'deposit.account_name': 'Non',
    'deposit.account_number': 'Nimewo',
    'deposit.crypto_warning': 'Voye sèlman kripto ki chwazi a sou rezo ki montre a. Nenpòt lòt voye ap pèdi.',
    'deposit.address': 'Adrès',
    'deposit.card_title': 'Peye ak kat mwen',
    'deposit.card_text': 'Ou pral redirije sou yon paj sekirize pou fini peman an.',
    'deposit.card_button': 'Peye kounye a',
    'deposit.card_link_missing': 'Lyen kat pa konfigire pa admin.',
    'deposit.reference_label': 'ID tranzaksyon / Referans',
    'deposit.reference_placeholder': 'Eg: MC-8392201',
    'deposit.receipt_label': 'Foto resi a',
    'deposit.upload_receipt': 'Telechaje foto',
    'deposit.submit': 'Soumèt depo a',
    'deposit.success_submitted': 'Depo a voye avèk siksè. An atant konfimasyon admin.',
    'deposit.error_load_config': 'Pa ka chaje konfigirasyon peman an',
    'deposit.error_loading': 'Erè chajman',
    'deposit.error_invalid_amount': 'Montan pa valab.',
    'deposit.error_min_amount': 'Montan minimòm se 2 USD.',
    'deposit.error_reference_required': 'ID tranzaksyon obligatwa.',
    'deposit.error_receipt_required': 'Foto resi obligatwa.',
    'deposit.error_rejected': 'Depo refize',
    'deposit.error_generic': 'Erè depo',
    'deposit.method.moncash': 'MonCash',
    'deposit.method.natcash': 'NatCash',
    'deposit.method.crypto': 'Kripto',
    'deposit.method.card': 'Kat',

    'withdraw.title': 'Retrè',
    'withdraw.subtitle': 'Chwazi metòd la epi soumèt demann ou an.',
    'withdraw.processing_title': 'Tretman estime',
    'withdraw.recipient_name': 'Non reseptè a',
    'withdraw.recipient_name_placeholder': 'Non konplè',
    'withdraw.recipient_phone': 'Nimewo reseptè a',
    'withdraw.recipient_phone_placeholder': 'Eg: +509...',
    'withdraw.crypto_network': 'Rezo kripto',
    'withdraw.destination_address': 'Adrès destinasyon',
    'withdraw.destination_placeholder': '0x...',
    'withdraw.submit': 'Soumèt retrè a',
    'withdraw.success_submitted': 'Demann retrè voye. Tretman manyèl an kou.',
    'withdraw.error_load_config': 'Pa ka chaje konfigirasyon peman an',
    'withdraw.error_loading': 'Erè chajman',
    'withdraw.error_invalid_amount': 'Montan pa valab.',
    'withdraw.error_recipient_required': 'Non ak nimewo reseptè obligatwa.',
    'withdraw.error_destination_required': 'Adrès kripto destinasyon obligatwa.',
    'withdraw.error_crypto_required': 'Chwazi yon rezo kripto.',
    'withdraw.error_rejected': 'Retrè refize',
    'withdraw.error_generic': 'Erè retrè',
    'withdraw.method.moncash': 'MonCash',
    'withdraw.method.natcash': 'NatCash',
    'withdraw.method.crypto': 'Kripto',

	    'dashboard.greeting': 'Byenveni',
	    'dashboard.title': 'Dachbòd',
	    'dashboard.welcome_back': 'Bon retou.',
	    'dashboard.welcome_back_named': 'Bon retou, {name}. Ann grandi ansanm.',
	    'dashboard.balance_title': 'Balans disponib',
	    'dashboard.current_board': 'Bòd aktyèl',
	    'dashboard.current_focus': 'Fokus aktyèl',
	    'dashboard.recent_activity': 'Aktivite resan',
	    'dashboard.recent_gains': 'Dènye benefis',
	    'dashboard.view_all': 'Wè tout',
	    'dashboard.deposit': 'Depoze',
	    'dashboard.go_boards': 'Al nan Bòd yo',
	    'dashboard.view_pyramid': 'Wè Piramid',
	    'dashboard.pending_in_boards': 'An atant (nan nivo yo)',
	    'dashboard.reserved': 'Rezève',
	    'dashboard.total_assets': 'Byen total',
	    'dashboard.level_label': 'Nivo',
	    'dashboard.progress_hint': 'Ou ap pwogrese byen. Envite plis moun pou akselere.',
	    'dashboard.view_level_details': 'Wè detay nivo a',
	    'dashboard.referral_progress': 'Pwogrè parennaj',
	    'dashboard.account_activation': 'Aktivasyon kont',
	    'dashboard.bonus_eligibility': 'Elijibilite bonis',
	    'dashboard.first_referral_unlock': 'Gains parennaj yo debloke depi premye filèl aktif ou. Pou pase nan pwochen board la, ou bezwen omwen 2 filèl aktif.',
	    'dashboard.your_code': 'Kòd ou',
	    'dashboard.root_owner': 'Pwopriyetè rasin',
	    'dashboard.position': 'Pozisyon',
	    'dashboard.join_starter': 'Rantre nan premye Bòd',
	    'dashboard.not_in_board': 'Pa nan okenn bòd aktif.',
	    'dashboard.no_recent_gains': 'Pa gen benefis resan',
	    'dashboard.no_activity': 'Pa gen aktivite resan.',
      'dashboard.na': 'N/A',

    'boards.title': 'Piramid Bòd yo',
    'boards.subtitle': '7 nivo progresif — F pou rive S',
    'boards.select': 'Chwazi',
    'boards.pay': 'Peye kotizan',
    'boards.fee': 'Kotizan',
    'boards.gain': 'Benefis total',
    'boards.members': 'manm',
    'boards.join': 'Rantre nan Bòd sa a',
    'boards.insufficient': 'Balans ensifizant',
    'boards.already_in': 'Deja manm',
    'boards.completed': 'Konplete',
    'boards.pending': 'An atant',
    'boards.page_title': 'CREATION BOARDS',
    'boards.page_subtitle': '7 nivo progresif soti F rive S',
    'boards.level': 'Nivo',
    'boards.board_label': 'Bòd',
    'boards.entry_cost': 'Pri antre',
    'boards.current_progress': 'Pwogrè aktyèl',
    'boards.step': 'Etap',
    'boards.not_active': 'Pa aktif',
    'boards.position': 'Pozisyon',
    'boards.step_progression': 'Pwogresyon etap pou',
    'boards.already_activated': 'Nivo ou deja aktive.',
    'boards.auto_activation_notice': 'Nivo sa a aktive otomatikman apre Board F fini.',
    'boards.insufficient_notice': 'Balans pa sifi. Depoze omwen ${amount} pou aktive nivo sa a.',
    'boards.processing': 'Ap trete...',
    'boards.activate_level': 'Aktive nivo sa a',
    'boards.activation_cost': 'Pri aktivasyon',
    'boards.wallet_balance': 'Balans bous',
    'boards.loading_levels': 'Ap chaje nivo yo...',
    'boards.step.starter': 'Starter',
    'boards.step.challenger': 'Challenger',
    'boards.step.leader': 'Leader',
    'boards.step.ranker': 'Ranker',
    'boards.theme.f': 'Foundation',
    'boards.theme.e': 'Expansion',
    'boards.theme.d': 'Development',
    'boards.theme.c': 'Consolidation',
    'boards.theme.b': 'Breakthrough',
    'boards.theme.a': 'Ascension',
    'boards.theme.s': 'Summit',

    'auth.login': 'Konekte',
    'auth.register': 'Enskri',
    'auth.email': 'Imèl',
    'auth.password': 'Modpas',
    'auth.username': 'Non itilizatè',
    'auth.first_name': 'Prenon',
    'auth.last_name': 'Siyati',
    'auth.referral_code': 'Kòd parennaj (obligatwa)',
    'auth.forgot_password': 'Bliye modpas?',
    'auth.no_account': 'Pa gen kont?',
    'auth.have_account': 'Genyen kont deja?',
    'auth.sign_in': 'Konekte',
    'auth.create_account': 'Kreye kont',
    'auth.register_now': 'Enskri kounye a',
    'auth.login_instead': 'Konekte',

    'verify.title': 'Verifye imèl ou',
    'verify.subtitle': 'Yo voye yon kòd verifikasyon bay',
    'verify.enter_code': 'Antre kòd 6 chif la',
    'verify.resend': 'Voye kòd ankò',
    'verify.resend_in': 'Voye ankò nan',
    'verify.verify': 'Verifye',
    'verify.back': 'Retounen nan koneksyon',

    'onboarding.step1': 'Chwazi lang ou',
    'onboarding.step2': 'Chwazi tèm ou',
    'onboarding.step3': 'Konfigire pwofil ou',
    'onboarding.step4': 'Kòd parennaj ou',
    'onboarding.continue': 'Kontinye',
    'onboarding.finish': 'Fini konfigirasyon',
    'onboarding.welcome': 'Byenveni sou Ecrossflow',
    'onboarding.step_of': 'Etap',
    'onboarding.of': 'nan',

    'history.title': 'Istwa',
    'history.subtitle': 'Tout tranzaksyon ou yo',
    'history.all': 'Tout',
    'history.deposit': 'Depo',
    'history.withdrawal': 'Retrè',
    'history.board_payment': 'Pèman Bòd',
    'history.board_receipt': 'Resi Bòd',
    'history.referral_bonus': 'Bonis Parennaj',
    'history.system_fee': 'Frè Sistèm',
    'history.no_transactions': 'Pa jwenn tranzaksyon',
    'history.previous': '← Anvan',
    'history.next': 'Swivan →',
    'history.page': 'Paj',
    'history.report': 'Rapò',
    'history.export_csv': 'Ekspòte CSV',
    'history.filters': 'Filtè',
    'history.status': 'Estati',
    'history.payment_method': 'Metòd peman',
    'history.date_from': 'Dat kòmansman',
    'history.date_to': 'Dat fen',
    'history.amount_min': 'Montan min (USD)',
    'history.amount_max': 'Montan max (USD)',
    'history.reset_filters': 'Reyajiste filtè yo',
    'history.adjust_filters': 'Eseye modifye filtè yo',
    'history.status_completed': 'Konplete',
    'history.status_pending': 'An atant',
    'history.status_processing': 'Ap trete',
    'history.status_cancelled': 'Anile',
    'history.view_report': 'Wè rapò detaye a',

    'referrals.title': 'Parennaj',
    'referrals.subtitle': 'Envite zanmi ou yo epi rantre bonis',
    'referrals.your_code': 'Kòd parennaj ou',
    'referrals.copy_code': 'Kopye kòd',
    'referrals.copy_link': 'Kopye lyen',
    'referrals.copied': 'Kopye !',
    'referrals.total': 'Total filèl',
    'referrals.active': 'Filèl aktif',
    'referrals.bonus': 'Bonis total',
    'referrals.no_referrals': 'Pa gen filèl pou kounye a',
    'referrals.share': 'Pataje kòd ou pou kòmanse !',
    'referrals.activation_title': 'Aktivasyon kont parennaj',
    'referrals.activation_done': 'Pwogram parennaj ou aktive !',
    'referrals.activation_needed': '{current}/{required} filèl aktif nesesè pou aktive bonis yo',
    'referrals.activation_left': 'Rete {left} filèl aktif pou debloke bonis yo.',
    'referrals.qr_show': 'Montre kòd QR',
    'referrals.share_hint': 'Pataje lyen oswa kòd sa a. Ou jwenn bonis lè filèl yo antre nan premye bòd yo.',
    'referrals.list_title': 'Filèl ou yo',
    'referrals.joined_on': 'Rantre le',
    'referrals.bonus_paid': 'Bonis peye',

    'notifications.title': 'Notifikasyon',
    'notifications.all': 'Tout',
    'notifications.unread': 'Pa li',
    'notifications.financial': 'Finansye',
    'notifications.security': 'Sekirite',
    'notifications.mark_all': 'Mete tout tankou li',
    'notifications.none': 'Pa gen notifikasyon',
    'notifications.unread_count': 'ki pa li',
    'notifications.loaded_all': 'Tout notifikasyon yo chaje',

    'profile.title': 'Pwofil',
    'profile.subtitle': 'Enfòmasyon ak preferans ou',
    'profile.account_number': 'Nimewo kont',
    'profile.email': 'Imèl',
    'profile.phone': 'Telefòn',
    'profile.current_board': 'Bòd aktyèl',
    'profile.referral_code': 'Kòd parennaj',
    'profile.member_since': 'Manm depi',
    'profile.theme': 'Tèm',
    'profile.language': 'Lang',
    'profile.save': 'Sove',
    'profile.not_set': 'Pa konfigire',

    'common.loading': 'Chajman...',
    'common.error': 'Te gen yon erè',
    'common.back': '← Retounen',
    'common.cancel': 'Anile',
    'common.confirm': 'Konfime',
    'common.save': 'Sove',
    'common.close': 'Fèmen',
    'common.or': 'oswa',
    'common.usd': 'USD',
    'common.status_active': 'Aktif',
    'common.status_pending': 'An atant',
    'common.status_suspended': 'Sispann',
  }
};

export const BASE_FR_TRANSLATIONS = translations.fr;

export const useAppStore = create<AppState>()(
  persist(
    (set, get) => ({
      theme: 'dark',
      language: 'fr',
      token: null,
      remoteMessages: {},
      setTheme: (theme) => {
        const root = document.documentElement;
        root.classList.remove('light', 'dark', 'midnight', 'gold');
        if (theme !== 'light') root.classList.add(theme);
        set({ theme });
      },
      setLanguage: (language) => set({ language }),
      setRemoteMessages: (remoteMessages) => set({ remoteMessages }),
      setToken: (token) => {
        if (token) localStorage.setItem('ecrossflow_token', token);
        else localStorage.removeItem('ecrossflow_token');
        set({ token });
      },
      logout: () => {
        localStorage.removeItem('ecrossflow_token');
        set({ token: null });
      },
      t: (key) => {
        const lang = get().language as CoreLanguage;
        const localPack = translations[lang] ?? translations.fr;
        const remote = get().remoteMessages[key];
        return remote || localPack[key] || translations.fr[key] || key;
      }
    }),
    { 
      name: 'ecrossflow-storage',
      partialize: (state) => ({ theme: state.theme, language: state.language, token: state.token }),
    }
  )
);
